export const SET_AMOUNT2 = "SET_AMOUNT2";
export const CHANGE_AMOUNT1 = "CHANGE_AMOUNT1";
export const SET_CURRENCY1 = "SET_CURRENCY1";
export const SET_CURRENCY2 = "SET_CURRENCY2";
export const SWAP_CURRENCY = "SWAP_CURRENCY";
